return function()
	require("alternate-toggler").setup({
		alternates = {
			["k"] = "v",
			["key"] = "val",
			["and"] = "or",
			["AND"] = "OR",
			["yes"] = "no",
			["Yes"] = "No",
			["YES"] = "NO",
			["on"] = "off",
			["On"] = "Off",
			["ON"] = "OFF",
			["max"] = "min",
			["Max"] = "Min",
			["MAX"] = "MIN",
			["let"] = "const",
			["true"] = "false",
			["True"] = "False",
			["TRUE"] = "FALSE",
			["break"] = "continue",
			["dark"] = "light",
			["left"] = "right",
			["Left"] = "Right",
			["inner"] = "outer",
			["Inner"] = "Outer",
			["local"] = "global",
			["public"] = "private",
			["1"] = "0",
			["<"] = ">",
			["("] = ")",
			["["] = "]",
			["{"] = "}",
			["+"] = "-",
			["=="] = "!=",
			["==="] = "!==",
			["<="] = ">=",
			["+="] = "-=",
			["&="] = "|=",
			["&&"] = "||",
			['"'] = "'",
			['""'] = "''",
			['"""'] = "'''",
			["~="] = { "==", "lua" },
			["="] = { ":=", "python" },
			["else"] = "elseif",
			["elif"] = { "else", "python" },
		},
	})
end
